name: Build

env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true    
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_NOLOGO: true    

on:
  push:
    branches: '*'
  pull_request:
    branches: 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0    

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Pack
      working-directory: src
      run: dotnet pack -c:Release

    - name: Push
      if: github.ref == 'refs/heads/main'
      run: dotnet nuget push "bin/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
