name: NuGet

on:
  push:
     tags: '*'

env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_NOLOGO: 1
    NUGET_AUTH_TOKEN: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}

defaults:
  run:
    working-directory: src

jobs:
  nuget:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1      
      with:
        dotnet-version: 7.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
            
    - name: Pack
      run: dotnet pack -c:Release
 
    - name: Test
      run: dotnet test

    - name: Push
      run: dotnet nuget push "../bin/Release/*.nupkg" -k ${{ secrets.NUGET_ORG_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
